# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1104, 756)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.stop_button = QtWidgets.QPushButton(self.centralwidget)
        self.stop_button.setObjectName("stop_button")
        self.gridLayout.addWidget(self.stop_button, 5, 1, 1, 2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.samp_freq_lbl = QtWidgets.QLabel(self.centralwidget)
        self.samp_freq_lbl.setObjectName("samp_freq_lbl")
        self.gridLayout.addWidget(self.samp_freq_lbl, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.run_lbl = QtWidgets.QLabel(self.centralwidget)
        self.run_lbl.setObjectName("run_lbl")
        self.gridLayout.addWidget(self.run_lbl, 4, 1, 1, 2)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 7, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.detc_lbl = QtWidgets.QLabel(self.centralwidget)
        self.detc_lbl.setObjectName("detc_lbl")
        self.gridLayout.addWidget(self.detc_lbl, 8, 1, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 6, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 8, 0, 1, 1)
        self.eng_lbl = QtWidgets.QLabel(self.centralwidget)
        self.eng_lbl.setObjectName("eng_lbl")
        self.gridLayout.addWidget(self.eng_lbl, 7, 1, 1, 1)
        self.run_button = QtWidgets.QPushButton(self.centralwidget)
        self.run_button.setObjectName("run_button")
        self.gridLayout.addWidget(self.run_button, 5, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.ard_con_lbl = QtWidgets.QLabel(self.centralwidget)
        self.ard_con_lbl.setObjectName("ard_con_lbl")
        self.gridLayout.addWidget(self.ard_con_lbl, 2, 1, 1, 2)
        self.cpi_lbl = QtWidgets.QLabel(self.centralwidget)
        self.cpi_lbl.setObjectName("cpi_lbl")
        self.gridLayout.addWidget(self.cpi_lbl, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.recv_data_lbl = QtWidgets.QLabel(self.centralwidget)
        self.recv_data_lbl.setObjectName("recv_data_lbl")
        self.gridLayout.addWidget(self.recv_data_lbl, 3, 1, 1, 2)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 9, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 9, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 7, 0, 1, 1)
        self.vel_lbl = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.vel_lbl.setFont(font)
        self.vel_lbl.setObjectName("vel_lbl")
        self.gridLayout.addWidget(self.vel_lbl, 9, 1, 1, 1)
        self.cpi_num_lbl = QtWidgets.QLabel(self.centralwidget)
        self.cpi_num_lbl.setObjectName("cpi_num_lbl")
        self.gridLayout.addWidget(self.cpi_num_lbl, 6, 1, 1, 2)
        self.raw_sig_radbutton = QtWidgets.QRadioButton(self.centralwidget)
        self.raw_sig_radbutton.setMaximumSize(QtCore.QSize(16777215, 28))
        self.raw_sig_radbutton.setObjectName("raw_sig_radbutton")
        self.gridLayout.addWidget(self.raw_sig_radbutton, 10, 0, 1, 1)
        self.vel_radbutton = QtWidgets.QRadioButton(self.centralwidget)
        self.vel_radbutton.setMaximumSize(QtCore.QSize(16777215, 28))
        self.vel_radbutton.setObjectName("vel_radbutton")
        self.gridLayout.addWidget(self.vel_radbutton, 10, 1, 1, 2)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.disp_plot = MplWidget(self.centralwidget)
        self.disp_plot.setMinimumSize(QtCore.QSize(680, 560))
        self.disp_plot.setMaximumSize(QtCore.QSize(99999, 99999))
        self.disp_plot.setObjectName("disp_plot")
        self.horizontalLayout.addWidget(self.disp_plot)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1104, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Speed Gun"))
        self.stop_button.setText(_translate("MainWindow", "Stop"))
        self.label.setText(_translate("MainWindow", "Sampling Frequency:"))
        self.samp_freq_lbl.setText(_translate("MainWindow", "0"))
        self.label_2.setText(_translate("MainWindow", "CPI:"))
        self.label_4.setText(_translate("MainWindow", "ms"))
        self.label_3.setText(_translate("MainWindow", "kHz"))
        self.run_lbl.setText(_translate("MainWindow", "No"))
        self.label_12.setText(_translate("MainWindow", "J"))
        self.label_6.setText(_translate("MainWindow", "Receiving Data:"))
        self.detc_lbl.setText(_translate("MainWindow", "No"))
        self.label_8.setText(_translate("MainWindow", "Current CPI:"))
        self.label_10.setText(_translate("MainWindow", "Detection:"))
        self.eng_lbl.setText(_translate("MainWindow", "0"))
        self.run_button.setText(_translate("MainWindow", "Run"))
        self.label_5.setText(_translate("MainWindow", "Arduino Connected:"))
        self.ard_con_lbl.setText(_translate("MainWindow", "No"))
        self.cpi_lbl.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "Running:"))
        self.recv_data_lbl.setText(_translate("MainWindow", "No"))
        self.label_11.setText(_translate("MainWindow", "Velocity:"))
        self.label_13.setText(_translate("MainWindow", "mph"))
        self.label_9.setText(_translate("MainWindow", "Energy:"))
        self.vel_lbl.setText(_translate("MainWindow", "0"))
        self.cpi_num_lbl.setText(_translate("MainWindow", "0"))
        self.raw_sig_radbutton.setText(_translate("MainWindow", "Raw Signal"))
        self.vel_radbutton.setText(_translate("MainWindow", "Velocity"))

from mplwidget import MplWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

